### ISSUE TITLE
No storage requirement detailed on Docs

### ISSUE THREAD

**Issue by NelsonGeeko** [rancher/rke2-docs#136]
Hi,

Currently the Hardware requirements page only references CPU and Memory as a hardware requirement. 

Recently while deploying Rancher on RKE2, We were in a resource restricted environment, the volumes that were assigned to the nodes were 10GB in size and were thick provisioned by underlying Hypervisor. While deploying Rancher using a Private Registry and the Air gapped Helm method, the install halted when the systems ran out of disc space.

Currently there is no reference to disc size for Rancher, only reference to the technologies that are recommended.

https://ranchermanager.docs.rancher.com/pages-for-subheaders/installation-requirements#disks

While we see more deployments in restricted infrastructures as well as at edge deployments, resources can often be constrained.

Can we please add some details on Minimum and Recommended sizes of volumes/discs to assist with these more resource constrained deployments.

**Comment by brandond** [comment]
> Currently there is no reference to disc size for Rancher

Are you talking about Rancher, or RKE2? 

We don't have a storage recommendation because the requirements are almost entirely driven by how you use your nodes.  At a bare minimum, you should have space for whatever airgap tarballs you are loading, plus the extracted images, plus the images for your workload, plus whatever temporary space your workload will require, plus sufficient free space to avoid exceeding the kubelet image garbage collection threshold.

> The volumes that were assigned to the nodes were 10GB in size

We could probably state a minimum for just the RKE2 components, but I can't imagine a scenario in which you can do anything useful at all with a 10 GB Kubernetes node.

**Comment by NelsonGeeko** [comment]
Sorry, yes this would be for Rancher, not RKE2.

**Comment by brandond** [comment]
OK. I'm going to close this then, as this is not the correct place to track asks for Rancher docs.
